### ISSUE TITLE
授权码哪里获取呢

### ISSUE THREAD

**Issue by gcc20200225** [BeHalcyon/fisher_script#1]

**Comment by ZhxnW** [comment]
你有授权码了吗

**Comment by BeHalcyon** [comment]
有效期12天
MDMwMDAwMTAwNzA4MTAwNTA1MDQwNDA4MDEwMjAxMDY=
MTUwMDAwMTAxNTA4MDIwNTA1MDQxMjA4MDkwMjEzMDY=
MTEwMDA4MTAxNTA4MDYwNTEzMDQwMDA4MDkwMjAxMDY=

**Comment by ZhxnW** [comment]
感谢您的回复！&nbsp; &nbsp; &nbsp;


我是有几个jd想参与一下抢券，部署了好几天，刚入门，想问后续授权码在哪里获取？可以留您的联系方式或者群嘛？


然后还有点问题就是图里的参数是哪里来的？需要自己抓包还是怎么填？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "BeHalcyon/fisher_script"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月22日(星期一) 晚上8:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [BeHalcyon/fisher_script] 授权码哪里获取呢 (Issue #1)





 
有效期12天
 MDMwMDAwMTAwNzA4MTAwNTA1MDQwNDA4MDEwMjAxMDY=
 MTUwMDAwMTAxNTA4MDIwNTA1MDQxMjA4MDkwMjEzMDY=
 MTEwMDA4MTAxNTA4MDYwNTEzMDQwMDA4MDkwMjAxMDY=

**Comment by BeHalcyon** [comment]
v:ByHalcyon
