### ISSUE TITLE
如何获取授权码？

### ISSUE THREAD

**Issue by jinshuqishi2019** [BeHalcyon/fisher_script#2]
你好，怎么才能获取授权码？大佬，有没有群可以加入？

**Comment by BeHalcyon** [comment]
20天内有效
UOfRKttq2x2TuV2C71vXH/afkYP1NMX2SXbX5DV7PjQ=

**Comment by jinshuqishi2019** [comment]
修改多次配置文件，还是提示Format Error in the configure file (fisher_configure.json)!

**Comment by BeHalcyon** [comment]
> 修改多次配置文件，还是提示Format Error in the configure file (fisher_configure.json)!

按README里的配置文件指导，删除中文条目

**Comment by jinshuqishi2019** [comment]
fisher_configure.json文件删除了中文条目，几乎是按照你例子抄，一些参数空白了，就是下面样子，运行检测就出现
```
[2022-08-25 07:44:25.466920]: Version: fisher_script:v1.4
[2022-08-25 07:44:25.467154]: Starting Coupon "plus"...
[2022-08-25 07:44:25.467229]: The "cookie_type" set to "mine".
Format Error in the configure file (fisher_configure.json)!

```
我是使用官方的python3.8.2的docker镜像下运行。

```
{
  "authorization_code": "",
  "interface":{
    "JDLITE_LOG_API": "",
    "JD_SIGN_API": "",
    "JD_SIGN_API_TOKEN": ""
  },
  "database": {
    "database_flag": "database_local",
    "database_remote": {
      "DATABASE_TYPE": "",
      "DATABASE_HOST": "",
      "DATABASE_PORT": "",
      "DATABASE_USER": "",
      "DATABASE_PASSWD": "",
      "DATABASE_DATABASE": ""
    }
  },
  "notification": {
    "WXPUSHER_APP_TOKEN": "",
    "WXPUSHER_UID": ""
  },
  "coupons": {
    "june-59-20": {
      "args": "key=m7abt6e3r4ica9l9cfm7scdf3dc82f59,roleId=80139254",
      "clock_list": [0, 10, 14, 20]
    },
    "june-10-9": {
      "args": "key=m1a8t3eer2i4a4l6c2m2s9bd982f3b98,roleId=81264321",
      "clock_list": [0, 10, 14, 20]
    },
    "39-8": {
      "activityId": "3H885vA4sQj6ctYzzPVix4iiYN2P",
      "discount": "8",
      "clock_list": [9, 12, 15, 18]
    },
    "30-5": {
      "activityId": "3H885vA4sQj6ctYzzPVix4iiYN2P",
      "discount": "5",
      "clock_list": [18]
    },
    "15-3": {
      "activityId": "3H885vA4sQj6ctYzzPVix4iiYN2P",
      "discount": "3",
      "clock_list": [0]
    },
    "34.9-34.89": {
      "activityId": "2doZYAgSAX6kiGmfrL4ZwLHzHHxa",
      "discount": "34.89",
      "clock_list": [14]
    },
    "1200-1040": {
      "activityId": "3bfYsYLqfqHvem9pNnVAAdyVLoR3",
      "discount": "1040",
      "clock_list": [20]
    }
  },
  "cookies": {
    "ws_cookies": [

    ],
    "plus_cookies": [

    ],
    "cookies": [

    ],
    "any_name_of_cookies": [

    ]
  }
}
```

**Comment by BeHalcyon** [comment]
> fisher_configure.json文件删除了中文条目，几乎是按照你例子抄，一些参数空白了，就是下面样子，运行检测就出现
> 
> ```
> [2022-08-25 07:44:25.466920]: Version: fisher_script:v1.4
> [2022-08-25 07:44:25.467154]: Starting Coupon "plus"...
> [2022-08-25 07:44:25.467229]: The "cookie_type" set to "mine".
> Format Error in the configure file (fisher_configure.json)!
> ```
> 
> 我是使用官方的python3.8.2的docker镜像下运行。
> 
> ```
> {
>   "authorization_code": "",
>   "interface":{
>     "JDLITE_LOG_API": "",
>     "JD_SIGN_API": "",
>     "JD_SIGN_API_TOKEN": ""
>   },
>   "database": {
>     "database_flag": "database_local",
>     "database_remote": {
>       "DATABASE_TYPE": "",
>       "DATABASE_HOST": "",
>       "DATABASE_PORT": "",
>       "DATABASE_USER": "",
>       "DATABASE_PASSWD": "",
>       "DATABASE_DATABASE": ""
>     }
>   },
>   "notification": {
>     "WXPUSHER_APP_TOKEN": "",
>     "WXPUSHER_UID": ""
>   },
>   "coupons": {
>     "june-59-20": {
>       "args": "key=m7abt6e3r4ica9l9cfm7scdf3dc82f59,roleId=80139254",
>       "clock_list": [0, 10, 14, 20]
>     },
>     "june-10-9": {
>       "args": "key=m1a8t3eer2i4a4l6c2m2s9bd982f3b98,roleId=81264321",
>       "clock_list": [0, 10, 14, 20]
>     },
>     "39-8": {
>       "activityId": "3H885vA4sQj6ctYzzPVix4iiYN2P",
>       "discount": "8",
>       "clock_list": [9, 12, 15, 18]
>     },
>     "30-5": {
>       "activityId": "3H885vA4sQj6ctYzzPVix4iiYN2P",
>       "discount": "5",
>       "clock_list": [18]
>     },
>     "15-3": {
>       "activityId": "3H885vA4sQj6ctYzzPVix4iiYN2P",
>       "discount": "3",
>       "clock_list": [0]
>     },
>     "34.9-34.89": {
>       "activityId": "2doZYAgSAX6kiGmfrL4ZwLHzHHxa",
>       "discount": "34.89",
>       "clock_list": [14]
>     },
>     "1200-1040": {
>       "activityId": "3bfYsYLqfqHvem9pNnVAAdyVLoR3",
>       "discount": "1040",
>       "clock_list": [20]
>     }
>   },
>   "cookies": {
>     "ws_cookies": [
> 
>     ],
>     "plus_cookies": [
> 
>     ],
>     "cookies": [
> 
>     ],
>     "any_name_of_cookies": [
> 
>     ]
>   }
> }
> ```

脚本里的cookie_type需要和配置里的cookies命名一致

**Comment by jinshuqishi2019** [comment]
我是直接运行 python exchange_check_coupons.py，检测得到的提示，还没有运行其他脚本。

**Comment by BeHalcyon** [comment]
> 我是直接运行 python exchange_check_coupons.py，检测得到的提示，还没有运行其他脚本。

对的，脚本里的cookie_type需要和配置里的cookies命名一致

**Comment by jinshuqishi2019** [comment]
即使添加cookie_type 也是不行。
```
root@python2:~/fisher_script/py38# python exchange_check_coupons.py --cookie_type cookies

[2022-08-26 09:52:03.911409]: Version: fisher_script:v1.4
[2022-08-26 09:52:03.911757]: Starting Coupon "plus"...
[2022-08-26 09:52:03.911790]: The "cookie_type" set to "cookies".
Format Error in the configure file (fisher_configure.json)!

```
exchange_check_coupons.py 这个文件不需要修改吧

**Comment by BeHalcyon** [comment]
> 即使添加cookie_type 也是不行。
> 
> ```
> root@python2:~/fisher_script/py38# python exchange_check_coupons.py --cookie_type cookies
> 
> [2022-08-26 09:52:03.911409]: Version: fisher_script:v1.4
> [2022-08-26 09:52:03.911757]: Starting Coupon "plus"...
> [2022-08-26 09:52:03.911790]: The "cookie_type" set to "cookies".
> Format Error in the configure file (fisher_configure.json)!
> ```
> 
> exchange_check_coupons.py 这个文件不需要修改吧

拉最新版，再看输出日志

**Comment by jinshuqishi2019** [comment]
谢谢了，更新了，运行就有错误提示，安装提示的模块就通过了。

**Comment by jinshuqishi2019** [comment]
大佬，还可以给个授权码吗？东西挺好用的。

**Comment by BeHalcyon** [comment]
> 大佬，还可以给个授权码吗？东西挺好用的。

简介里有
