### ISSUE TITLE
脚本可以更新支持python3.10吗？

### ISSUE THREAD

**Issue by jinshuqishi2019** [BeHalcyon/fisher_script#4]
现在的新安装(apt install python)的python 默认最新的python3.10，系统指定特点版本安装有点麻烦，希望能够有支持python3.10的版本，谢谢。
还有一个问题，对于shortkey，将body拼接在url中，post_flag=False，运行后显示乱码和运行错误。

**Comment by BeHalcyon** [comment]
> 现在的新安装(apt install python)的python 默认最新的python3.10，系统指定特点版本安装有点麻烦，希望能够有支持python3.10的版本，谢谢。 还有一个问题，对于shortkey，将body拼接在url中，post_flag=False，运行后显示乱码和运行错误。

1. 后期可以考虑增加10版本，可以先用pyenv和conda增加版本控制
2. short key不允许body添加参数，且request的固定方式为post，请在配置文件中添加，并配合exchange_lib的接口传递。如果需要自定义request(如get)，需要熟悉抓到包的格式并配准(如headers限定的域、序列化格式、ua，body的格式，返回的类型等)

**Comment by jinshuqishi2019** [comment]
谢谢你解答并提供解决方法。
我还以为post_flag=False ，就是get，因为我测试发现使用get比post更好。按照你的说法改get请求对我有不少困难，那现在只能用着post方法运行。
